name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  freezed_annotation: ^3.0.0
  build_runner: ^2.4.15
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  vit_gpt_dart_api: ^5.1.0
  intl: ^0.20.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/texts/
